/* catalog.js — the knowledge base about every file in a Niantic Pokémon GO
 * GDPR/data export. Used by the landing page (to teach people what Niantic
 * stores) and by the app (to recognise uploaded files and label their story).
 *
 * Each entry:
 *   id        canonical filename (or folder for Player_Journey)
 *   match     RegExp tested against the uploaded file's name (case-insensitive)
 *   name      friendly title
 *   icon      emoji
 *   group     bucket used for grouping in the catalog UI
 *   summary   one-line description
 *   contains  plain-English list of what's inside
 *   columns   the actual raw column names Niantic ships (transparency)
 *   sensitivity 'high' | 'medium' | 'low'  — how revealing the RAW file is
 *   sensitivityNote  why
 *   story     what THIS site can build from it (null = nothing chartable)
 *   retention rough note on how far back Niantic's copy goes
 */
window.CATALOG = [
  {
    id: "Gameplay.txt",
    match: /gameplay\.txt$/i,
    name: "Gameplay Summary",
    icon: "🎮",
    group: "Your Profile",
    summary: "Your lifetime account snapshot — level, XP, distance, your whole collection and every medal.",
    contains: [
      "Trainer name, start date, level and total XP",
      "Pokécoin and Stardust balances",
      "Lifetime distance walked and eggs hatched",
      "Every Pokémon currently in your storage (by species)",
      "Every medal/badge and its tier (bronze → platinum)",
      "Your whole bag, item by item, plus the eggs and incubators you're holding",
      "A rolling log of your last session — spins, catches and flees with their CP",
      "(also: your Nintendo/Pokémon Home account IDs and referral code — ignored here)",
    ],
    columns: ["Trainer name", "Start date", "Level", "Total XP", "Pokecoin", "Stardust", "Distance walked", "Eggs hatched", "Collection (per species)", "Badges (per medal, with tier)", "Items (per item, with count)", "Nintendo Account ID", "Referral code"],
    sensitivity: "low",
    sensitivityNote: "Almost all of it is a game summary — no email, no address, no payment data. It does end with your account IDs and referral code, which this site never reads.",
    story: "Your trainer card, a collection breakdown by region (Kanto → Paldea), your most-hoarded species, your medal cabinet, what's in your bag, and a close-up of the last day you played.",
    retention: "Lifetime snapshot — current account state.",
  },
  {
    id: "Player_Journey",
    match: /^(pokestop_spin|sfida_capture|map_pokemon_encounter|join_raid_lobby|gym_battle|feed_pokemon|deploy_pokemon|incense_encounter|lure_encounter)\d*\.csv$/i,
    name: "Player Journey events",
    icon: "🗺️",
    group: "Your Activity",
    summary: "A timestamped log of nearly everything you did — every spin, catch, raid, gym battle and berry, with coordinates.",
    contains: [
      "Pokéstop spins, with the stop's location",
      "Catches (GO Plus / Auto Catch) and map encounters",
      "Raid lobbies joined, with the gym's location",
      "Gym battles, berries fed, Pokémon deployed",
      "Incense and Lure encounters",
      "A timestamp and your GPS position for most events",
    ],
    columns: ["Player_Latitude", "Player_Longitude", "Gym_Latitude", "Gym_Longitude", "Fort_Latitude", "Fort_Longitude", "Timestamp"],
    sensitivity: "high",
    sensitivityNote: "Precise coordinates and timestamps for thousands of events — this can reveal your home, work and daily routine. Handle with care.",
    story: "The big one: your activity timeline month-by-month, your hour-of-week play rhythm, totals for every action type, remote-raid detection (how far your raids reached), and a heatmap of where you played.",
    retention: "Niantic keeps roughly the last 3 years of events.",
  },
  {
    id: "GameplayLocationHistory.tsv",
    match: /gameplaylocationhistory\.tsv$/i,
    name: "Location History",
    icon: "📍",
    group: "Your Activity",
    summary: "A high-resolution GPS trail of where the game saw you, point by point.",
    contains: ["A timestamp", "Latitude and longitude reported by the game"],
    columns: ["Date and Time", "Latitude of location reported by game", "Longitude of location reported by game"],
    sensitivity: "high",
    sensitivityNote: "The single most sensitive file — a literal map of your movements. Niantic only keeps a short window, but treat it carefully.",
    story: "A day-by-day GPS trail drawn on the map, showing your routes and the area you covered.",
    retention: "Short rolling window — usually the last ~2 months only.",
  },
  {
    id: "FriendList.tsv",
    match: /friendlist\.tsv$/i,
    name: "Friend List",
    icon: "🤝",
    group: "Your Social World",
    summary: "Everyone you're currently friends with, when you became friends, and how.",
    contains: [
      "Each friend's codename and nickname",
      "The date your friendship started",
      "Who sent the friend request",
      "How you connected (QR, nearby, Friend Graph…)",
      "Which Niantic games you share",
    ],
    columns: ["Friend's codename", "Date of friendship start", "Friendship initiated by", "Friendship Source", "Nickname", "Games they are Friends in"],
    sensitivity: "medium",
    sensitivityNote: "Contains other people's codenames/nicknames. It's your social graph, so share screenshots thoughtfully.",
    story: "Your friendships over time, your oldest and longest-running friends, how you usually connect, who reaches out first, and which games overlap.",
    retention: "Current friends — a live snapshot.",
  },
  {
    id: "RecentlyUnfriended.tsv",
    match: /recentlyunfriended\.tsv$/i,
    name: "Recently Unfriended",
    icon: "💔",
    group: "Your Social World",
    summary: "Friendships that ended recently.",
    contains: ["Name of the unfriended trainer", "Date and time it happened"],
    columns: ["Name of unfriended friend", "Date and time"],
    sensitivity: "medium",
    sensitivityNote: "Names of people you removed. Low stakes, but still other people's data.",
    story: "Friendship churn — how many connections ended, and when, layered onto your friend-growth chart.",
    retention: "Short rolling window — about the last 4 months.",
  },
  {
    id: "RecentInviteActions.tsv",
    match: /recentinviteactions\.tsv$/i,
    name: "Recent Invite Actions",
    icon: "✉️",
    group: "Your Social World",
    summary: "Your recent friend-invite activity — sent, accepted and declined.",
    contains: ["The action (sent / accepted / declined)", "Date and time", "The other codename", "Result"],
    columns: ["Action", "Timestamp", "Codename", "Result"],
    sensitivity: "medium",
    sensitivityNote: "Includes other trainers' codenames.",
    story: "Your invite funnel — how many requests you sent vs. accepted vs. declined in Niantic's recent window.",
    retention: "Short rolling window — about the last 4 months.",
  },
  {
    id: "ActivityInvitesReceived.tsv",
    match: /activityinvites(received|sent)\.tsv$/i,
    name: "Party Play Invites",
    icon: "🎉",
    group: "Your Social World",
    summary: "Party Play / activity invites you sent and received.",
    contains: ["Activity type", "Date and time of invite", "Expiration time"],
    columns: ["Activity type", "Date and time of invite (UTC)", "Expiration time (UTC)"],
    sensitivity: "low",
    sensitivityNote: "Just invite types and timestamps.",
    story: "How much you used Party Play — invites sent and received, counted alongside your friend-request activity.",
    retention: "Short rolling window.",
  },
  {
    id: "InAppPurchases.tsv",
    match: /inapppurchases\.tsv$/i,
    name: "In-App Purchases",
    icon: "💳",
    group: "Your Spending",
    summary: "Your complete money-and-coins ledger — every Pokécoin bought and spent.",
    contains: [
      "Pokécoins bought, with the real money paid and currency",
      "Pokécoins spent on in-game items",
      "In-game items bought directly",
      "The vendor (App Store, Google Play, web…)",
      "A timestamp for each transaction",
    ],
    columns: ["Date and time", "Type of activity", "Vendor", "Item purchased", "Number of items", "Change in pokecoins", "Money spent on purchase", "Currency"],
    sensitivity: "medium",
    sensitivityNote: "Real spending amounts and currencies. No card numbers, but it's your financial activity in the game.",
    story: "Your spending story: total real money by currency, coins bought vs. spent over time, which items you buy most, which storefront you buy from, and the free daily boxes and support gifts in the same ledger.",
    retention: "Long history of transactions.",
  },
  {
    id: "FitnessData.tsv",
    match: /fitnessdata\.tsv$/i,
    name: "Adventure Sync Fitness",
    icon: "🏃",
    group: "Your Fitness",
    summary: "Steps, distance and calories that Adventure Sync logged.",
    contains: ["Logging timestamp", "Steps walked", "Distance in meters", "Calories burned", "Exercise duration", "Wheelchair distance"],
    columns: ["Date and time of logging (UTC)", "Steps walked", "Distance travelled (meters)", "Calories burned", "Exercise duration (minutes)", "Wheelchair distance (meters)"],
    sensitivity: "medium",
    sensitivityNote: "Health-adjacent activity data. Niantic only keeps a short window.",
    story: "Your movement: daily steps and distance, totals, and fun real-world equivalents (marathons, etc.).",
    retention: "Short rolling window — about the last 3 weeks.",
  },
  {
    id: "App_Sessions.csv",
    match: /app_sessions\.csv$/i,
    name: "App Sessions",
    icon: "📱",
    group: "Technical & Device",
    summary: "Every time you opened the app — with device and approximate city.",
    contains: ["Session timestamp", "Device model", "Platform / OS version", "Approximate city, state & country", "(also: IP, ad IDs, postal code — which this site ignores)"],
    columns: ["Event_time", "Device_model", "Platform", "City", "State", "Country_code", "IP", "Advertising_ID", "Postal_code", "IDFA", "…"],
    sensitivity: "high",
    sensitivityNote: "The raw file also holds your IP address, postal code and advertising identifiers. This site reads only session counts, device, city and country — never the identifiers.",
    story: "How often you played over time, the devices you used, the cities you logged in from, and the countries you've played in — the one map that needs no GPS file at all.",
    retention: "Long session history.",
  },
  {
    id: "App_Installs.csv",
    match: /app_installs\.csv$/i,
    name: "App Installs",
    icon: "⬇️",
    group: "Technical & Device",
    summary: "When and where you installed the app.",
    contains: ["Install timestamp", "Platform", "Device model", "(also: IP, ad IDs, postal code — ignored here)"],
    columns: ["Install_time", "Platform", "Device_model", "IP", "Postal_code", "Advertising_ID", "…"],
    sensitivity: "high",
    sensitivityNote: "Raw file includes IP and postal code. This site reads only install date, platform and device model.",
    story: "Your install timeline and the devices you've played on.",
    retention: "All-time install records.",
  },
  {
    id: "User_Attribution_Sessions.csv",
    match: /user_attribution_sessions\.csv$/i,
    name: "Attribution Sessions",
    icon: "🛰️",
    group: "Technical & Device",
    summary: "Marketing/attribution data — IPs, device and advertising IDs.",
    contains: ["IP address", "Device & advertising IDs", "Timezone, region, city"],
    columns: ["Device_IP_Address", "Application_Device_ID", "Apple_Advertiser_ID", "Google_Play_Store_Advertising_ID", "City", "…"],
    sensitivity: "high",
    sensitivityNote: "Almost entirely identifiers and IPs. There's nothing meaningful to visualise, so this site deliberately ignores it.",
    story: null,
    retention: "Marketing attribution records.",
  },
  {
    id: "ImageData.txt",
    match: /imagedata\.txt$/i,
    name: "Photo / Image Data",
    icon: "📸",
    group: "Your Activity",
    summary: "GO Snapshot and AR photos you took, by date.",
    contains: ["An opaque image reference", "The date and time it was uploaded"],
    columns: ["Image ID", "Upload Date"],
    sensitivity: "low",
    sensitivityNote: "References and dates only — never the picture itself, and never where it was taken. The least revealing file in the export.",
    story: "Your photo album: how many GO Snapshots you've taken, the months you shot the most, and your single biggest photo day.",
    retention: "Rolling window — roughly the last two years.",
  },
  {
    id: "wayfarer_player_data.json",
    match: /wayfarer_player_data\.json$/i,
    name: "Wayfarer Contributions",
    icon: "🧭",
    group: "Your Activity",
    summary: "Your Pokéstop/portal nominations and reviews as a Wayfarer.",
    contains: ["Submission log (nominations)", "Review/agreement stats", "(also: your home coordinates & email — ignored here)"],
    columns: ["OprSubmissionLog", "OprProfile (Total Analyzed, Portals Created…)", "OprSkippedLog"],
    sensitivity: "high",
    sensitivityNote: "The raw profile can contain your home coordinates and email. This site reads only aggregate review/creation counts.",
    story: "How much you've contributed to the map — nominations made and reviews completed.",
    retention: "All-time Wayfarer record.",
  },
  {
    id: "LiveEventRegistrationHistory_AsPurchaser.tsv",
    match: /liveeventregistrationhistory_aspurchaser\.tsv$/i,
    name: "Live Event Tickets",
    icon: "🎟️",
    group: "Your Spending",
    summary: "Tickets you bought for GO Fest, Safari Zone and other live events.",
    contains: ["Event name and dates", "Tickets and add-ons", "Total paid and currency", "(also: email, order #, phone carrier — ignored here)"],
    columns: ["Date of Order Placed", "Event Details", "Number of Tickets on Order", "AddOn Info", "Total Paid", "Currency Paid", "Email Used", "Order Number"],
    sensitivity: "high",
    sensitivityNote: "Raw file contains your email, order numbers and in-game names. This site reads only event name, dates, ticket counts and amount paid.",
    story: "The live events you attended and what you spent to be there.",
    retention: "All-time order history.",
  },
  {
    id: "LiveEventRegistrationHistory_GiftedOrRedeemedTickets.tsv",
    match: /liveeventregistrationhistory_giftedorredeemedtickets\.tsv$/i,
    name: "Gifted Event Tickets",
    icon: "🎁",
    group: "Events",
    summary: "Event tickets you gave away or were given.",
    contains: ["Ticket transfer records (usually empty)"],
    columns: ["Event details", "Ticket info", "Date"],
    sensitivity: "low",
    sensitivityNote: "Usually empty. Niantic ships the file either way.",
    story: null,
    retention: "As applicable.",
  },
  {
    id: "LiveEventRegistrationHistory_Refund.tsv",
    match: /liveeventregistrationhistory_refund\.tsv$/i,
    name: "Event Ticket Refunds",
    icon: "↩️",
    group: "Events",
    summary: "Refunds on live-event tickets.",
    contains: ["Refund records (usually empty)"],
    columns: ["Event details", "Refund amount", "Date"],
    sensitivity: "low",
    sensitivityNote: "Usually empty. Niantic ships the file either way.",
    story: null,
    retention: "As applicable.",
  },
  {
    id: "SupportInteractions1.tsv",
    match: /supportinteractions\d*\.tsv$/i,
    name: "Support Interactions",
    icon: "🛟",
    group: "Technical & Device",
    summary: "Your support tickets with Niantic.",
    contains: ["Ticket number and title", "Date and time", "(message content — ignored here)"],
    columns: ["Date and time", "Ticket number and title", "Message content", "Custom Fields", "Meta data"],
    sensitivity: "medium",
    sensitivityNote: "Message bodies can contain anything you wrote to support. This site reads only the date and the subject line, never the text.",
    story: "How many times you've contacted Niantic, when, and what about — including the ticket that produced this very export.",
    retention: "Support history.",
  },
  {
    id: "AccountInformation.txt",
    match: /accountinformation\.txt$/i,
    name: "Account Information",
    icon: "🔐",
    group: "Identity (not visualised)",
    summary: "The core identifiers tied to your account.",
    contains: ["Email address", "Account IDs", "Account creation details"],
    columns: ["Email", "Account ID", "…"],
    sensitivity: "high",
    sensitivityNote: "This is your identity. There's nothing to chart and every reason not to — this site never reads it.",
    story: null,
    retention: "Current account.",
  },
  {
    id: "SocialProfile.txt",
    match: /socialprofile\.txt$/i,
    name: "Social Profile",
    icon: "🪪",
    group: "Identity (not visualised)",
    summary: "Your friend-invite code and notification preferences.",
    contains: ["Friend invite code", "Notification settings"],
    columns: ["Invite code", "Notification preferences"],
    sensitivity: "medium",
    sensitivityNote: "Your invite code is a way to be added. Nothing to visualise.",
    story: null,
    retention: "Current settings.",
  },
  {
    id: "ContactsImport.txt",
    match: /contactsimport\.txt$/i,
    name: "Contacts Import",
    icon: "📇",
    group: "Identity (not visualised)",
    summary: "Whether you opted into contact-based friend suggestions.",
    contains: ["Opt-in flag", "Display name"],
    columns: ["Opt-in", "Display name"],
    sensitivity: "low",
    sensitivityNote: "Just a flag and a name. Nothing to chart.",
    story: null,
    retention: "Current setting.",
  },
  {
    id: "DrawingEntryHistory.tsv",
    match: /drawingentryhistory\.tsv$/i,
    name: "Sweepstakes Entries",
    icon: "🎲",
    group: "Your Spending",
    summary: "Prize-drawing / sweepstakes entries.",
    contains: ["Entry records (often empty)"],
    columns: ["Entry details"],
    sensitivity: "low",
    sensitivityNote: "Usually empty.",
    story: null,
    retention: "As applicable.",
  },
  {
    id: "LiveEventLeaderboard.tsv",
    match: /liveeventleaderboard\.tsv$/i,
    name: "Live Event Leaderboard",
    icon: "🏅",
    group: "Events",
    summary: "Your placement in live-event leaderboards.",
    contains: ["Leaderboard entries (often empty)"],
    columns: ["Leaderboard details"],
    sensitivity: "low",
    sensitivityNote: "Usually empty.",
    story: null,
    retention: "As applicable.",
  },
];

/* Find the catalog entry for an uploaded filename (basename). */
window.catalogFor = function (filename) {
  const base = (filename || "").split("/").pop();
  return window.CATALOG.find((c) => c.match.test(base)) || null;
};
